run:
  timeout: 2ms
  tests: true
  concurrency: 4

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: ".*defer.*Close.*"
